#!/bin/bash
#
# enver 2.0
#
# Liefert die Uebersetzung eines englische Verbs aus einer Woerterbuchdatei von "dict.cc".
#
# Fuer eine Bedienungsanleitung "source enver --help" aufrufen!
#
# Stand: 2018-03-15
# Autor: Bernd Storck
#
# Veroeffentlicht via "https://www.facebook.com/BStLinux/"
#

script_name="enver"
vocabulary="dictverbs.txt"
Tab="	"

function default_output() {
	local searched="$1"
	# grep -P "^[[:blank:]]*(to )\b$searched\b\t" "$vocabulary" | tr "\t" "#" | column -s"#" -t
	# return "$(grep -c -P "^[[:blank:]]*(to )\b$searched\b\t" "$vocabulary")"
	grep -E "^[[:blank:]]*(to )\<$searched\>$Tab" "$vocabulary" | tr "\t" "#" | column -s"#" -t
	return "$(grep -c -E "^[[:blank:]]*(to )\<$searched\>$Tab" "$vocabulary")"

}

function print_all_verbs() {
	local searched="$1"
	local counter
	grep -E "^[[:blank:]]*(to )\<$searched\>.*$Tab" "$vocabulary" | tr "\t" "#" | column -s"#" -t > /tmp/enver.tmp
	if test -s /tmp/enver.tmp; then
		counter="$(wc -l '/tmp/enver.tmp' | cut -d" " -f1)" 
		if [[ "$counter" -gt 24 ]]; then
			if [ "$(which less)" ]; then
				less -S /tmp/enver.tmp
			elif [ "$(which most)" ]; then
				most /tmp/enver.tmp
			else
				more /tmp/enver.tmp
			fi
		else
			cat /tmp/enver.tmp
		fi
	else
		counter=0
		echo "Kein Datensatz, keine Erklärung zu \"$searched\" gefunden." > /dev/stderr
	fi
	rm -f /tmp/enver.tmp
	return $counter
}

function print_full() {
	# The following search string contains three tab characters between the first
	# pair of quotation marks!  With a perl expression the following would be:
	# grep -P "^[^#][^\t]+([^\[][^\[\]]*)$2.*[^\]][^\t]*\t" "$vocabulary"

	local searched="$1"
	# grep -E "^[^#][^$Tab]+([^\[][^\[\]]*)$1.*[^\]][^$Tab]*$Tab" "$vocabulary" | \
	grep -E "^[^#\[][^$Tab\[]+([^\[][^\[\]]*)$1.*[^\]][^$Tab]*$Tab" "$vocabulary" | \
	grep --color=always "$1"  
	return $?
}	

function print_all() {
	# Fields are separated by tabs.  First field is English, second German. 
	# Finds all records/lines with the searched string in the first field, 
	# even if it is a part of a word.  
	#
	# As perl expression this would be: grep -P "^[^#][^\t]+$2[^\t]*\t" "$vocabulary"
	#
	# The following search string contains three tab characters between the first 
	# pair of quotation marks!
	local searched="$1"
	grep --color=always -E "^[^#][^$Tab]+$1[^$Tab]*$Tab" "$vocabulary" 
	return "$?"
}

function phrases() {
	local searched="$1"
	grep -e "^[[:blank:]]*[A-Z]" -e "\[Redewendung\]" -e "\[idiom\]" "$vocabulary" | \
	sed "s/\[Redewendung\]//" | grep -iE "^[[:blank:]]*[^	]*\<$searched\>.*	" | \
	grep --color=always -wi "$searched" | tr "\t" "#" | column -s"#" -t
}

function write_amount_of_phrases() {

	local searched="$1"
	local amount_of_phrases=$(grep -e "^[[:blank:]]*[A-Z]" -e "\[Redewendung\]" -e "\[idiom\]" "$vocabulary" | \
	grep -c -iE "^[[:blank:]]*[^	]*\<$searched\>.*	")

	if [ "$amount_of_phrases" -gt 0 ]; then

		echo -n "\"$script_name -P $searched\" liefert $amount_of_phrases " > /dev/stderr
		if [ "$amount_of_phrases" -gt 1 ]; then
			local object_name="Datensätze"
		else
			local object_name="Datensatz"
		fi
		echo "$object_name." > /dev/stderr
	
	fi
}

function write_total_amount() {

	local searched="$1"
	local amount=$(grep -c -E "^[[:blank:]]*(to )\<$searched\>.*	" "$vocabulary")

	if [ "$amount" -gt 0 ]; then

		echo -n -e  "\n\"$script_name -V $searched\" liefert $amount " > /dev/stderr
		if [ "$amount" -gt 1 ]; then
			local object_name="Datensätze"
		else
			local object_name="Datensatz"
		fi
		echo "$object_name." > /dev/stderr
	
	fi
}


display_help_screen() {
 	echo "$script_name"
	echo -e "\t\"$script_name\" zeigt Übersetzungen englischer Verben ins Deutsche an."
	echo -e "\nAUFRUFFORMAT:"
	echo -e "\t$script_name [-v|-V|-D|-P|-p|-f|-a|-h] VOKABEL"
	echo -e "\nBEISPIELE:"
	echo -e "\t$script_name -v translate"
	echo -e "\t$script_name translate"
	echo -e "\n\t(Beiden Aufrufe bewirken das selbe. \"translate\" ist hier das Wort, nach dem gefragt wird.)"
	echo -e "\nAUFRUFPARAMETER:";
	echo -e "\t-v\tLiefert eine kurze Auskunft über ein englisches Verb."
	echo -e "\t-V\tSucht nur nach englischen Verben und listet alle dazu verfügbaren Datensätze auf."
	echo -e "\t-D\tSucht von einem deutschen Wort aus nach nach englischen Verben."
	echo -e "\t-P\tFindet Redewendungen (engl. \"phrases\") und Sätze mit der Zeichenkette."
	echo -e "\t-p\tKombiniert \"-v\" (kurze Auskunft) mit \"-P\" (Liste von Redewendungen)."
	echo -e "\t-f\tZeigt Datensätze mit der gesuchten Zeichenkette im englischen Text."
	echo -e "\t-a\tZeigt alle Datensätze mit der gesuchten Zeichenkette im englischen Text."
	echo -e "\t-h\tZeigt diese Hilfeseite an."
	echo -e "\nALTERNATIVE SPRECHENDE AUFRUFPARAMETER:";
	echo -e "\t-v \t--verb"
	echo -e "\t-V \t--verbs"
	echo -e "\t-D \t--deutsch, --de-en"
	echo -e "\t-P \t--phrases"
	echo -e "\t-p \t--phrases-too"
	echo -e "\t-f \t--full"
	echo -e "\t-a \t--all, --alle, --alles"
	echo -e "\t-h \t--help"
}


case $1 in

  -V|--verbs)
	# Long list about the searched verb:
	print_all_verbs "$2"
	if [ "$?" -eq 0 ]; then
		sleep 1
		echo
		echo "Weitergehende Suche auch nach Wortteilen startet." > /dev/stderr
		sleep .75
		print_full "$2"
		if [ "$?" -ne 0 ]; then
			echo "Weitergehende Suche ohne Ergebnis." > /dev/stderr
			echo
			sleep .5
			echo "Suche nach jedem Vorkommen des Such-Strings startet." > /dev/stderr
			print_all "$2"
			if [ "$?" -ne 0 ]; then
				echo "Die gesuchte Zeichenkette kommt im englischen Teil der Datenbasis nicht vor." > /dev/stderr
			fi
		fi
	fi
	;;

  -v|--verb)
	# "Short list, simple info about a verb:
	default_output "$2"
	if [ $? -ne 0 ]; then
		write_total_amount "$2"
		write_amount_of_phrases "$2"
	else  # if "enver -v" does not succeed, automatically execute "enver -V":
		print_all_verbs "$2"
	fi
	;;

  -g|-d|-G|-D|--de-en|--german|--deutsch)
	# Find a verb to a german word:
	grep -E "^[[:blank:]]*(to ).*$Tab.*\<$2\>" "$vocabulary" | tr "\t" "#" | column -s"#" -t
	;;

  -p|--phrases-too|phrases_too)
	# Find also phrases, combines "-v" with "-P":
	default_output "$2"
	echo
	phrases "$2"
	write_total_amount "$2"
	;;

  -P|--phrases)
	# Find and write only phrases:
	phrases "$2"
	;;

  -f|--full)
	# Finds a string even if it is a part of a word.  
	print_full "$2"
	;;

  -a|--all|--alle|--alles)
	# Finds all records/lines with the searched string in English.
	print_all "$2"
	;;

  -h|--help)
	display_help_screen
	;;

  *)
	# Short list, simple info about a verb, same action as with "-v":
	default_output "$1"
	if [ $? -ne 0 ]; then
		write_total_amount "$1"
		write_amount_of_phrases "$1"
	else  # if "enver -v" does not succeed, automatically execute "enver -V":
		print_all_verbs "$1"
	fi
	;;

esac


